### ISSUE TITLE
In ruby, this un-comments the previous line

### ISSUE THREAD

**Issue by benbuckman** [ctf0/vscode-auto-comment-next-line#1]
I added `ruby` to the config:
```json
      "char": "#",
      "languages": [
        "python",
        "ruby"
      ]
    }
```

Now when I am on a comment line, and press Enter, it makes a new line and _un-comments_ the line I was previously on.

**Comment by ctf0** [comment]
i have just tested it and its working, here is my editor info
```
Version: 1.48.0-insider
Commit: 15ada625f20086007e2c4aa0d760234360cd648f
Date: 2020-07-30T14:46:01.621Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```

maybe u have another ext that does that ?

**Comment by xcskier56** [comment]
I have found this issue as well with ruby. 

```
Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z (2 wks ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
```

Edit:
I wonder if this is due to conflicts with some ruby package. This is working for python and terraform which both use `#` for comments

Edit 2: 
I have disabled all packages that deal with ruby and this is still happening... don't know why

**Comment by ctf0** [comment]
@xcskier56 will give it another try today

**Comment by ctf0** [comment]
@xcskier56 
its working 

```
Version: 1.77.0-insider
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T09:55:12.120Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

maybe there is a difference between the insider vs stable builds, but can u try to install the insider build and try again ?
