### ISSUE TITLE
Any support for .jsx files?

### ISSUE THREAD

**Issue by eriegz** [ctf0/vscode-auto-comment-next-line#2]
Hi, are there any plans to add support for .jsx files? I've already tried adding the file extension to the "languages" array of in the settings.json file, i.e.:

```
"autoCommentNextLine.list": [
  {
    "char": "//",
    "languages": [
      ...
      "jsx"
    ]
  },
}
```

...but no dice.

**Comment by ctf0** [comment]
is jsx a language in vscode ?

**Comment by eriegz** [comment]
No, it's not.

After digging a little more, I learned that .jsx files are officially supported in VS Code under the language names "javascriptreact" and "typescriptreact". So this would imply that we could add support for .jsx files by adding these to the aforementioned "languages" array, i.e.:

```
"autoCommentNextLine.list": [
  {
    "char": "//",
    "languages": [
      ...
      "javascriptreact",
      "typescriptreact"
    ]
  },
}
```

...but this still doesn't work. Any advice?

**Comment by ctf0** [comment]
its working correctly on my end
- open jsx file "language will be set to react automatically"
- comment something
- press enter

**Comment by eriegz** [comment]
Yeah, it's not working for me on VS Code version 1.52.1 (and "Auto Comment Next Line" version 0.1.0).

And just to be clear, your VS Code automatically sets language to "JavaScript React", not "React", right? See below:

![vs-code](https://user-images.githubusercontent.com/10801672/107100786-983f2400-67d2-11eb-86a4-05511d52c4b6.jpg)

So any tips on troubleshooting this? E.g.: can you paste your settings.json `"autoCommentNextLine.list"` value here?

**Comment by ctf0** [comment]
i've updated the ext with all my settings including support for jsx, maybe we have different copies of vscode mine is
```
Version: 1.54.0-insider
Commit: 52838cf6799cc448e738677ec37e86cf62a5bd89
Date: 2021-02-05T05:15:00.813Z
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

![remo](https://user-images.githubusercontent.com/7388088/107101126-f72a8a80-681e-11eb-972f-669fa56ebba0.png)

**Comment by eriegz** [comment]
This is weird... I finally got it to work, but it's unstable and "breaks" again any time some external program touches the file (e.g.: GitKraken, if you use the "Discard changes" button).

Here's how I got it to work:

- Copy the contents of the file
- Delete the file
- Create a new file with the same name
- Paste the contents into the file and save it
- Now "Auto Comment Next Line" works

And then here's how it breaks again:

- Open GitKraken
- Find the comment you just added (assuming you saved the file)
- Click "Discard Hunk" or right-click > "Discard changes"
- Now back in VS Code "Auto Comment Next Line" breaks again

I acknowledge that you appear to be on macOS and using a slightly newer version of VS Code than me, but I think there may be something unstable in the way that the extension handles .jsx files.

**Comment by ctf0** [comment]
its not that hard to debug really, the whole thing it a nutshell
https://github.com/ctf0/vscode-auto-comment-next-line/blob/3a97d06e58c2fbdd42a775ab1255d793f474d54c/extension.js#L16-L37

- we check if there is an editor opened
- listen to enter key press
- check if prev line has a comment
- run `editor.action.commentLine`

**Comment by eriegz** [comment]
Yeah, I saw that actually. Looking through your extension's source code was the first thing I did before opening this issue. 😄

In any case, I'll decide how much I want to troubleshoot this later... You know the old joke about programmers:

- Do a task that takes 5 seconds? ❌
- Spend 3 hours learning how to automate that task: ✔

**Comment by ctf0** [comment]
> Do a task that takes 5 seconds? ❌
Spend 3 hours learning how to automate that task: ✔

🤣

**Comment by eriegz** [comment]
Aha, I just stumbled upon the root cause, and why we don't see it on macOS:

Turns out this extension doesn't work with "LF" line endings, only "CRLF".

(My VS Code creates new files with CRLF as the default line ending, but then GitKraken would convert them to LF when it made changes)

**Comment by ctf0** [comment]
it actually works on both, but the eol is dependent on the os, so using something different wont work.

**Comment by ctf0** [comment]
u can fix this by using a one eol across all ur files, in vscode add to settings
```json
"files.eol": "\n"
```

**Comment by eriegz** [comment]
Yeah I actually fixed my problem by doing the ol' `git config --global core.autocrlf false`. 🙂
